const projects=[
{title:"Personal Brand Identity",category:"branding",label:"Branding",image:"images/personal-brand-identity.png",desc:"A personal visual identity system developed for Daniel Cecil Christian, including logo, colour palette, typography and branded applications."},
{title:"Dan & Ann Liquid Soap Logo",category:"branding",label:"Branding",image:"images/dan-ann-liquid-soap-logo.png",desc:"Logo development for Dan & Ann Liquid Soap, exploring a fresh and friendly identity for a consumer product brand."},
{title:"Dan & Ann Brand Guide",category:"branding",label:"Branding",image:"images/dan-ann-brand-guide.jpg",desc:"A brand guide showing identity applications, colour, layout and supporting visual elements for Dan & Ann Liquid Soap."},
{title:"Gboza Fresh Tilapia Label",category:"branding",label:"Branding",image:"images/gboza-fresh-tilapia-label.jpg",desc:"Packaging label design combining product information, nutrition details and a clear retail presentation."},
{title:"Exhibition Portfolio Cover",category:"editorial",label:"Editorial Design",image:"images/exhibition-portfolio-cover.png",desc:"Cover design for an exhibition portfolio, bringing together photography, typography and project information."},
{title:"Exhibition Portfolio Spread",category:"editorial",label:"Editorial Design",image:"images/exhibition-portfolio-spread.png",desc:"Interior portfolio spread demonstrating editorial structure, visual hierarchy and project presentation."},
{title:"Editorial Illustration — 01",category:"editorial",label:"Editorial Design",image:"images/editorial-project-01.png",desc:"Editorial visual exploring environmental themes through illustration, composition and image-making."},
{title:"Editorial Illustration — 02",category:"editorial",label:"Editorial Design",image:"images/editorial-project-02.png",desc:"Editorial illustration exploring social and workplace themes through conceptual imagery."},
{title:"Galamsey Awareness Poster",category:"graphic-design",label:"Graphic Design",image:"images/galamsey-poster.jpg",desc:"An awareness poster addressing the impact of illegal mining through a direct message and documentary-style presentation."},
{title:"Digital Printing — Colour Study",category:"graphic-design",label:"Graphic Design",image:"images/digital-printing-01.jpg",desc:"A printed colour study exploring colour combinations, reproduction and visual consistency."},
{title:"Typography Print Study",category:"graphic-design",label:"Graphic Design",image:"images/typography-print-study.jpg",desc:"A typographic print study focused on letterforms, composition and the physical qualities of printed design."},
{title:"Digital Printing — Applications",category:"graphic-design",label:"Graphic Design",image:"images/digital-printing-02.jpg",desc:"Printed design applications demonstrating colour, layout and production."},
{title:"Social Media Graphics",category:"graphic-design",label:"Graphic Design",image:"images/social-media-graphics.jpg",desc:"Social media graphics created to communicate product information and brand messaging in digital spaces."},
{title:"ATL FM Promotional Graphics",category:"graphic-design",label:"Graphic Design",image:"images/atl-fm-promotional-graphics.jpg",desc:"Promotional graphic design combining programme information, photography and typography for audience engagement."},
{title:"CBS Motion Graphics",category:"photo-video",label:"Photo / Video",image:"images/cbs-motion-graphics.png",desc:"Motion graphics work exploring visual identity, screen composition and animated broadcast communication."},
{title:"Broadcast Graphics & Editing",category:"photo-video",label:"Photo / Video",image:"images/broadcast-graphics.jpg",desc:"Broadcast and video-editing workflow showing screen graphics, timeline editing and visual storytelling."}
];
const grid=document.getElementById("grid"), lb=document.getElementById("lightbox"), img=document.getElementById("lbimg"), title=document.getElementById("lbtitle"), cat=document.getElementById("lbcat"), desc=document.getElementById("lbdesc");let visible=[...projects],current=0;
function render(filter="all"){visible=filter==="all"?[...projects]:projects.filter(p=>p.category===filter);grid.innerHTML=visible.map((p,i)=>`<article class="card" data-i="${i}" tabindex="0"><div class="pic"><img src="${p.image}" alt="${p.title}"></div><div class="meta"><div><h3>${p.title}</h3><p>${p.label}</p></div><span>↗</span></div></article>`).join("");document.querySelectorAll(".card").forEach(c=>{c.onclick=()=>open(+c.dataset.i);c.onkeydown=e=>{if(e.key==="Enter")open(+c.dataset.i)}})}
function open(i){current=i;let p=visible[i];img.src=p.image;img.alt=p.title;title.textContent=p.title;cat.textContent=p.label;desc.textContent=p.desc;lb.classList.add("open");document.body.style.overflow="hidden"}
function close(){lb.classList.remove("open");document.body.style.overflow=""}function next(){open((current+1)%visible.length)}function prev(){open((current-1+visible.length)%visible.length)}
document.querySelectorAll(".filters button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");render(b.dataset.filter)});
document.querySelector(".close").onclick=close;document.querySelector(".next").onclick=next;document.querySelector(".prev").onclick=prev;lb.onclick=e=>{if(e.target===lb)close()};document.onkeydown=e=>{if(!lb.classList.contains("open"))return;if(e.key==="Escape")close();if(e.key==="ArrowRight")next();if(e.key==="ArrowLeft")prev()};
const menu=document.querySelector(".menu");menu.onclick=()=>document.querySelector("nav").classList.toggle("open");document.querySelectorAll("nav a").forEach(a=>a.onclick=()=>document.querySelector("nav").classList.remove("open"));document.getElementById("year").textContent=new Date().getFullYear();render();